spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

logging:
  config: classpath:log4j2.properties

springdoc:
  swagger-ui:
    path: /swagger-ui.html